spring:
  datasource:
    url: jdbc:h2:file:./demo
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: none

demo:
  customer-details:
    name: customer-details-import
    file-path: 'classpath:customer-details.csv'
    field-names:
    - number
    - type
    - name
    line-to-skip: 1
